---
title: "Iris"
author: "Valencia"
format: html
editor: visual
---

This is a R code to visualization iris dataset. It splits the data into three subplot by Species.

___

*Step 
## 1. Load library
```{r}
library(ggplot2)
```

- ggplot2 is a package for drawing charts in R
- library() is a function to read a package


## 2. Draw scatter plot
```{r}
  iris_plot <- ggplot(iris, aes(x=Sepal.Length, y = Sepal.Width))+
  geom_point() +
  facet_grid(. ~ Species)
```
geom_point:
   - Draw a scatter plot
-`facet_grid(. ~ Species)` :
   - Splits the plot into seperate panels for each 'Species'
## 3. Prepare Labels
```{r}
g_labels <- data.frame(Species = c("setosa", "versicolor", "virginica"), 
                       label=c("Setosa", "Versicolor", "Virginica"))
```
## 4. Add labels to the plot
```{r}
iris_plot +
  geom_text(x = 7, y = 4, aes(label = label), data = g_labels) +
  labs(title = "Iris",
       x = "Sepal length",
       y = "Sepal width",
       caption = "By Valencia, Data Visualization course, Tunghai University, 2024")+
  theme(plot.title = element_text(hjust = 0.5, size = 20))
```
```{r}

library(ggplot2)
  iris_plot <- ggplot(iris, aes(x=Sepal.Length, y = Sepal.Width))+
  geom_point() +
  facet_grid(. ~ Species)
```
```{r}
g_labels <- data.frame(Species = c("setosa", "versicolor", "virginica"), 
                       label=c("Setosa", "Versicolor", "Virginica"))
```
```{r}
iris_plot +
  geom_text(x = 7, y = 4, aes(label = label), data = g_labels) +
  labs(title = "Iris",
       x = "Sepal length",
       y = "Sepal width",
       caption = "By Valencia, Data Visualization course, Tunghai University, 2024")+
  theme(plot.title = element_text(hjust = 0.5, size = 20))
```
##
